{{- $replicas := int .Values.replicas -}}
{{- range $i := until $replicas }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
  name: {{ include "lighthouse.fullname" . }}-claim{{ $i | add 1 }}
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  selector:
    {{- toYaml .Values.persistence.selector | nindent 8 }}
status: {}
{{- end }}
