apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ include "lighthouse.fullname" . }}
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
spec:
  #type: NodePort
  ports:
    - name: "p2p-tcp"
      port: 30301
      targetPort: 30301
    - name: "p2p-udp"
      port: 30301
      protocol: UDP
      targetPort: 30301
    - name: "http-api"
      port: 5052
      targetPort: 5052
    - name: "metrics"
      port: 5054
      targetPort: 5054
  selector:
    {{- include "lighthouse.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
