apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.fullname" . }}-jwt
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
